.gitignore
I'm assuming as we're all on macs this could happen to any of us so I'm including in the public gitignore instead of my private one.
=> Add mac ds store files to git ignore

client/src/app/ui/UiConfirm.vue, client/src/helpers/ehr-actions.js, client/src/inside/components/EhrNavPanel.vue, client/src/inside/components/EhrNavPanelAction.vue
This commit just provides the confirmation dialog that will be used by students to submit their work.  Will continue this client side work once some server side work is completed.
=> Setup evaluation confirmation

client/src/App.vue, client/src/app/components/AppHeader.vue, client/src/helpers/ehr-actions.js, client/src/helpers/ehr-helper.js, client/src/inside/components/EhrContextInstructor.vue, client/src/inside/components/EhrContextStudent.vue, client/src/outside/components/AssignmentsListing.vue, client/src/outside/components/ClassList.vue, client/src/outside/components/EhrSeedDataList.vue, client/src/store/modules/ehrData.js, client/src/store/modules/instructor.js, client/src/store/modules/visit.js, server/src/controllers/activity-controller.js, server/src/controllers/activity-data-controller.js, server/src/controllers/lti.js
Add submit and evaluated properties
Add actions to set state in the app.
Instructor/student actions to mange submitted and evaluated state.
App wide css class isInstructor or isStudent
Remove development stuff that was on the instructor pages.
=> Submitted and Evaluated states

deployment/mac-dev.site, server/package.json, server/src/config/env/development.js, server/src/controllers/lti.js
Adjustments for running prod like on mac and DO server
=> Deployment setup

.gitignore, client/src/helpers/ehr-helper.js, client/src/inside/components/EhrCalculatedValue.vue, client/src/inside/components/EhrDialogForm.vue, client/src/inside/components/EhrDialogFormElement.vue, client/src/inside/components/Vitals.vue, client/src/inside/components/VitalsChart.vue, client/src/outside/components/ClassList.vue, client/src/outside/components/EhrSeedDataList.vue, server/package.json, server/src/controllers/lti.js
Plus:
hide some debug messages.
change start dev script to match pattern of other scripts
Seed data page, fix actions, fix edit raw ehr data
Calculated values now can have html labels
Update git ignore
=> Vitals open dialog button

client/src/App.vue, client/src/app/components/AppHeader.vue, client/src/helpers/store-helper.js, client/src/inside/components/EhrContextInstructor.vue, client/src/inside/components/EhrSpecial.vue, client/src/outside/components/ClassList.vue, client/src/store/modules/ehrData.js, client/src/store/modules/instructor.js, client/src/store/modules/storeHelper.js, server/src/controllers/lti.js
as user selects a class list update the storage.
as instructor user selects student in class list load this student's data
create a helper class to hold methods to access common data and dispatch routines in the storage modules
=> Instructor evaluation

client/src/helpers/ehr-actions.js, client/src/inside/components/EhrContextInstructor.vue, client/src/outside/components/ClassList.vue, client/src/outside/views/Dashboard.vue, client/src/scss/_definitions.scss
=> Update dashboard to be more user friendly

client/src/inside/components/EhrDialogFormElement.vue
The dialog needed to follow the example set at the page form level
=> Issue 240 fix checkbox layout

client/src/helpers/vitalModel.js, client/src/inside/components/Vitals.vue, client/src/inside/components/VitalsChart.vue, client/src/store/modules/system.js
Vital set scroll position on reload
=> Vitals extend canvas size and add sample data option

client/src/app/components/AppDialogShell.vue, client/src/app/components/AppFooter.vue, client/src/app/components/AppHeader.vue, client/src/app/components/SystemMessage.vue, client/src/app/ui/UiButton.vue, client/src/inside/components/EhrBanner.vue, client/src/inside/components/EhrContextBanner.vue, client/src/inside/components/EhrContextStudent.vue, client/src/inside/components/EhrNavPanel.vue, client/src/inside/components/EhrNavPanelAction.vue, client/src/inside/components/EhrPageForm.vue, client/src/inside/components/EhrPageFormElement.vue, client/src/inside/components/mar/MarTodayContent.vue, client/src/inside/layout/LayoutEhr.vue, client/src/main.js, client/src/scss/_definitions.scss, client/src/scss/styles.scss
Removed a bunch of unused/unneeded styles, streamlined code, polished exisiting component styles
@bryan-gilbert I took the flash message layout of of an ul but it seems to have broken the functionality and I can't figure out how to get it back. Can you jump in this branch before you merge and hook that up again for me please?
=> Polish and simplify

client/src/App.vue, client/src/app/components/SystemMessage.vue, client/src/app/ui/UiInfo.vue, client/src/helpers/ehr-defs.js, client/src/inside/components/EhrContextBanner.vue, client/src/inside/components/EhrDialogFormElement.vue, client/src/inside/components/EhrNavPanel.vue, client/src/inside/components/EhrPageFormElement.vue, client/src/inside/components/EhrPageFormLabel.vue, client/src/inside/components/Vitals.vue, client/src/inside/defs/current-visit-1.js, client/src/inside/defs/current-visit-2.js, client/src/inside/defs/external-resources.js, client/src/inside/defs/patient-chart.js, client/src/inside/defs/patient-profile.js, client/src/inside/defs/test-page.js, makeEhr/generators/raw-input-to-def.js, makeEhr/hashMapFile.json, server/test/controllers/assignmentController.spec.js
helper text into dialogs
UiInfo has optional html content
=> Generator; suffix, help text. Eval button full width

client/src/helpers/store-helper.js, client/src/outside/components/AsInstructor.vue, client/src/outside/components/ClassList.vue, client/src/outside/components/EhrSeedDataDialog.vue, client/src/outside/components/EhrSeedDataList.vue, client/src/store/modules/assignment.js, server/src/config/seed-data/consumers.js, server/src/config/text.js, server/src/mcr/assignment/assignment-controller.js, server/src/mcr/consumer/consumer-controller.js, server/src/mcr/lti/lti.js
Client side:
seed list shows activities
classlist component loads activtity to get freshest data, it also checks for externalId (see isse #289)
Server side
tool consumer - default text properties simplified
assignment controller -- find by external id
=> client: seed list , classlist. server: tool consumer, assignment

client/src/helpers/ehr-text.js, client/src/helpers/ehr-utills.js, client/src/outside/components/EhrSeedDataList.vue
See https://github.com/BCcampus/edehr/issues/201
Importing a seed file checks for this license.
text messages come from common source
=> Seed files now have Creative Commons license. Issue #201

client/src/inside/components/EhrNavListItem.vue, client/src/inside/components/tables/EhrPageTableStacked.vue, client/src/inside/components/tables/EhrPageTableVertical.vue
For instructor reviewing student's work, the NavPanel now shows Orange dot if there is seed data
=> Tables show 'no data' if none avail

client/src/inside/components/EhrNavListItem.vue, client/src/main.js
I know the icons looks squished atm, but once there's only one on the right side the spacing should sort itself out.
We need to use different icons + colour for the status so it's colour-blind friendly. :)
=> Styles for nav status

client/src/app/components/AppDialogShell.vue
I was also able to make the modal fit the content when it’s less thanf ull screen by swapping out `height` for `max-height`
=> Reduce modal structure code

client/src/outside/components/AssignmentsDialog.vue, client/src/outside/components/AssignmentsListing.vue, client/src/outside/components/ClassList.vue, client/src/outside/components/EhrSeedDataList.vue
Make table header names consistent with page and button labels
Swap font awesome icons in for text `+` and `-`
=> Clean up dashboard

client/src/helpers/ehr-defs-grid.js, client/src/inside/components/page/EhrCommonElement.vue, client/src/inside/components/page/EhrDialogForm.vue, client/src/inside/components/page/EhrGroup.vue, client/src/inside/components/page/EhrPage.vue, client/src/inside/components/page/EhrPageElement.vue, client/src/inside/components/page/EhrPageForm.vue, client/src/inside/components/page/EhrPageTable.vue, client/src/inside/components/page/EhrSubGroup.vue, client/src/inside/components/page/EhrTableCommon.vue, client/src/inside/components/page/EhrTableStacked.vue, client/src/inside/components/page/ehr-helper.js, client/src/inside/defs-grid/test-page.js, makeEhrV2/generators/input-to-def.js
This commit introduces the dialogs that come with tables.  It also takes the first steps for tables with stacked columns. Just need to hook up the data save methods to populate the table so there can be some data to layout.
=> another step -- tables dialogs

client/src/inside/components/page/EhrElementCommon.vue, client/src/inside/components/page/EhrPage.vue, client/src/inside/components/page/EhrPageTable.vue, client/src/inside/components/page/EhrTableCommon.vue, client/src/inside/components/page/EhrTableStacked.vue, client/src/inside/components/page/EhrTableVertical.vue, client/src/inside/components/page/ehr-helper.js, client/src/inside/defs-grid/test-page.js, client/src/store/modules/ehrData.js, makeEhrV2/generators/input-to-def.js, makeEhrV2/raw_data/test-page.txt
page and seed save
table save and load
table stacked display
deep copy the row template
=> advancing gridwork 

client/src/helpers/ehr-text.js, client/src/helpers/store-helper.js, client/src/outside/components/Activity.vue, client/src/outside/components/ClassList.vue, server/src/mcr/activity/activity-controller.js
show evaluation notes in class list
show correct student name and last visit in the ehr context panel.
clear up some displayed text
=> Fix some issues for instructor

client/src/helpers/ehr-helper.js, client/src/inside/components/mar/MarSummary.vue, client/src/inside/components/mar/mar-helper.js, client/src/inside/components/mar/mar-summary.js, client/src/inside/components/page/EhrDialogForm.vue, client/src/inside/components/page/EhrElementCalculated.vue, client/src/inside/components/page/EhrElementCheckset.vue, client/src/inside/components/page/ehr-calcs.js, client/src/inside/components/page/ehr-helper.js, client/src/inside/defs-grid/current-visit-1.js, client/src/inside/layout/LayoutEhr.vue, makeEhrV2/raw_data/current-visit-1.txt
=> checksets V2

client/src/inside/components/page/EhrGroup.vue, client/src/inside/components/page/EhrPageForm.vue, client/src/inside/components/page/EhrPageFormControls.vue, client/src/inside/components/page/EhrTableVertical.vue, client/src/inside/components/page/ehr-helper.js, client/src/inside/defs-grid/current-visit-1.js, client/src/inside/defs-grid/current-visit-2.js, client/src/inside/defs-grid/external-resources.js, client/src/inside/defs-grid/patient-chart.js, client/src/inside/defs-grid/patient-profile.js, client/src/inside/defs-grid/test-page.js, makeEhrV2/gen_defs/generate-ehr-defs.js, makeEhrV2/gen_defs/input-to-def.js, makeEhrV2/hashMapFile.json
Form edit buttons, css precedence, table css
Use  ui-button for form edit controls
override css on group wrappers if css is defined in Inputs
add tableCss to transposed table elements
Group class
if the class from the INPUTS does not include grid then add the default 3-col class
=> restart storage of hashes from code generation

deployment/bccampus-server/bccampus-nginx.conf, erin-johns-seed.json
and stash the Erin Jones seed in the repo
=> save the bc campus nginx file

client/src/inside/components/page/EhrElementCommon.vue, client/src/inside/components/page/ehr-helper.js, client/src/inside/defs-grid/current-visit-1.js, client/src/inside/defs-grid/current-visit-2.js, client/src/inside/defs-grid/external-resources.js, client/src/inside/defs-grid/patient-chart.js, client/src/inside/defs-grid/patient-profile.js, client/src/inside/defs-grid/test-page.js, makeEhrV2/gen_defs/ehr-short-forms.js, makeEhrV2/gen_defs/helps.js, makeEhrV2/gen_defs/input-to-def.js, makeEhrV2/hashMapFile.json, makeEhrV2/raw_data/patient-profile.txt
Implement the checkbox_text_spacer short form. https://github.com/BCcampus/edehr/issues/467
missing table column just WARN because it might be by design. 
Load the DataCaseStudy values into the pages when developing a seed.  When course designer edits the form AND then saves it they get these case study values into the seed. https://github.com/BCcampus/edehr/issues/441
=> tableColumn, checkbox_text_spacer and seed reload with Data Case Study

client/src/directives/text-to-html.js, client/src/inside/components/page/ehr-helper.js, client/src/outside/components/Activity.vue, client/src/outside/layout/LayoutOutside.vue, docs/developer/visit-state.md, server/package.json
Fix the "is developing content" checkbox. Had two watch declarations and that broke the functionality.
- code clean
- document visit state for later
- adjust server startup commands
Fix the descriptions on the activity (dashboard). They were not showing up because the text-to-html directive only handled bind and not update.
Fix the directive too.
Change layout on Activity to arrange content in table so the row headers are more clearly visible
=> Fix descriptions and develop content

client/src/app/components/AccordionElement.vue, client/src/app/components/AppHeader.vue, client/src/app/ui/UiButton.vue, client/src/outside/components/Activity.vue, client/src/outside/layout/LayoutOutside.vue, client/src/outside/views/Instructor.vue, client/src/scss/styles/_tables.scss
I also renamed `Dashboard` to `Courses` It just makes more sense!
=> Style updated dashboard

client/src/scss/_definitions.scss, client/src/scss/styles/_tables.scss, docs/configuration/README.md
Adjust table styles to deal with updated font size
Minor spelling error fix
=> Update font size

client/src/helpers/store-helper.js, client/src/outside/components/ConsumerDialog.vue, client/src/outside/components/ConsumerListing.vue, client/src/outside/views/Consumers.vue, client/src/outsideRoutes.js, client/src/store/index.js, client/src/store/modules/consumerListStore.js, server/src/mcr/admin/admin-controller.js, server/src/mcr/consumer/consumer-controller.js
Add method to add tool consumers
Remove unused admin routes in server
Need this consumer tool for pilot setup
=> Consumer page, edit and create

client/src/inside/components/discharge/DischargeV2.vue, client/src/inside/components/discharge/ehr-summary-tableV2.js, client/src/inside/defs-grid/current-visit-2.js, makeEhrV2/hashMapFile.json, makeEhrV2/raw_data/current-visit-2.txt
https://github.com/BCcampus/edehr/issues/385
Depends on changes made to the inputs sheet.  Named version 'Dec 21 - 2 discharge'
=> Split the Discharge page to have two forms $385

docs/.vuepress/config.js, docs/student/README.md
Re: chat with Dave - Student documentation is not needed.
=> Remove student section

client/src/store/modules/consumerListStore.js, server/package.json, server/src/config/config.js, server/src/config/env/development.js, server/src/config/env/test.js, server/src/mcr/admin/admin-server.spec.js, server/src/mcr/consumer/consumer.spec.js, server/src/server/api.js
With more developers involved I need to be more careful to run the linter and tester before every PR.  This is a catch up. 
- move the new create consumer tests into the consumer spec file
- fix lint errors
- fix loading of the test environment configuration on the server side.
=> Lint and Tests

client/src/inside/components/page/EhrDependant.vue, client/src/inside/components/page/EhrGroup.vue
the dependent on object needs to be reactive
=> dependancy - fix reactivity

CONTRIBUTING.md, docs/developer/contributors.md, docs/developer/devop/deploy.md, docs/developer/devop/technical-architecture.md, docs/developer/visit-state.md, docs/getting-started.md
Also removed some spaces from other files
=> WIP - editing dev docs

makeMeds/convertMedication.js
Change the tool that generates the medication "database".  It'll now produce a file with JSON.
=> Make meds -- create json objects

client/src/outside/components/ActivityListItem.vue
=> Fix routing

client/src/inside/layout/LayoutEhr.vue
=> Chore:  move ehr-context-banner position in Ehr Layout file

client/src/inside/components/chart/VitalsChart.vue
=> Chore: Improve scale for axisCanvas when useScale is enabled

client/src/inside/components/page/EhrDependent.vue, client/src/inside/components/page/ehr-helper.js, client/src/main.js
After pressing Save the form went blank.  Just had to invoke page load.
Also fixing error with EhrDependent when the event channel is undefined.
Lint main after addition of vue autosuggest
=> Fix editing seed data

client/src/app/ui/UiConfirm.vue
Allow customizing the cancel button text.
=> UiConfirm - add cancel button label property

client/src/app/components/AppDialogShell.vue
Tried various things to better display the date picker.  For now we'll just fix the dialog height.
This is a rebase and squash of https://github.com/BCcampus/edehr/pull/535
=> Fix dialog height.

client/src/inside/components/EhrContextInstructor.vue, client/src/inside/components/EhrEvaluationInput.vue
=> Improve textarea display after saving in the save and next / previous flow

client/src/inside/components/page/EhrElementCommon.vue, client/src/inside/components/page/EhrElementForm.vue, client/src/inside/components/page/EhrElementLookup.vue
=> Improve lookahead

client/src/inside/components/EhrContextInstructor.vue
This addresses the issue mentioned on Slack, which happened when trying to go back to classlist in the evaluation panel
=> Fix classList list which was breaking in EhrContextInstructor

client/src/App.vue, client/src/router.js
=> Change validation of authentication to meta property

client/src/outside/components/AssignmentsDialog.vue, client/src/outside/components/ConsumerDialog.vue, server/package.json
add debug stmt to dialog validation
=> Fix deployment

client/src/outside/components/AssignmentsDialog.vue, client/src/outside/components/AssignmentsListing.vue
Allow numbers at start of externalId
Use standard styles in assignment listing
=> Assignments

client/src/helpers/ehr-actions.js, client/src/inside/components/EhrNavPanelAction.vue
=> Implement notification dialog when submitting student data

client/src/app/components/AppDialogShell.vue
Remove body's position for outside routes
=> Fix layout breaking when creating new assignment modal is opened 

client/src/app/components/AppDialogShell.vue, client/src/outside/components/EhrSeedDataDialog.vue, client/src/outside/components/EhrSeedDataList.vue, client/src/store/test/_data/upload-seed-data.json
=> Move Upload logic inside the Create/Update seed Modal

client/src/app/components/AppDialogShell.vue, client/src/outside/components/AssignmentsDialog.vue, client/src/outside/components/AssignmentsListing.vue, client/src/outside/components/EhrSeedDataDialog.vue, client/src/scss/_definitions.scss
Fix footer in dialogs,
remove advanced sections no longer needed in Assignment and Seed dialogs
Change warning colour and position of message on the Assignments page.
=> Dialog adjustments

client/src/inside/components/EhrNavPanelAction.vue
=> Implement Feedback dialog

client/src/inside/components/page/EhrPageForm.vue
It was too close to the form and too tempting to click
=> Move the reset form button off to the side

database/backup/backup.sh, database/backup/restore.sh, database/docker-compose.yml, deployment/d-c.yml, deployment/database/backup.sh, deployment/database/restore.sh, package.json
=> Implement backup scripts for local and production

client/src/App.vue
Patches a bug reported on #565, which was preventing the page of being properly shown.
=> Move authentication logic to watcher instead of created

client/src/outside/components/ClassList.vue
=> Fix 500 status on ClassList page

client/src/outside/components/ClassList.vue
=> Improve assign submission display on course list 

client/src/outside/components/EhrSeedDataDialog.vue
Add requested comment from #578
=> Add object-comparison comment to EhrSeedDataDialog

client/src/app/ui/UiConfirm.vue, client/src/outside/components/EhrSeedDataList.vue
=> Implement duplication of seeds

client/src/inside/components/page/EhrPageForm.vue
=> Disable reset button when form is being edited

client/src/inside/components/EhrBanner.vue
=> Make weight field in banner reactive

client/src/store/modules/ehrDataStore.js
=> Fix page content indicators on tables

client/src/outside/components/AssignmentsListing.vue
=> Fix description fields in assignments not being properly cleared out

README.md, database/docker-compose.yml, deployment/d-c.yml, package.json
This PR implements comments to both the README file as well as in the scriptComments in package.json. Also, it implements an improved and common folder structure for production and deployment both
=> Comment instructions for database recovery

client/src/inside/components/page/EhrPageTable.vue
=> Move clear-table button to the right

client/src/app/ui/UiLink.vue, client/src/outside/components/ActivityListItem.vue
ActivityList -- load class list page with id via query string
UI Link allow pass param by query
=> Fix activity list loading and page refresh

client/src/app/ui/UiAgree.vue, client/src/inside/components/EhrNavPanelAction.vue
Display a confirmation dialog.
=> After student submits

client/src/outside/components/ClassList.vue
Pilot program found that we need to show the student name to help import the results.
=> Add fields to activity evaluation download

client/src/main.js, server/src/mcr/activity/activity-controller.js
Clear the date closed when reopening the activity.
Fix the date format directives to handle null
=> Fix activity date closed issue

client/src/app/components/AppDialogShell.vue, client/src/inside/components/page/EhrDialogForm.vue
=> Improve the way errors are displayed on AppDialogShell

server/package.json, server/src/mcr/lti/lti.js, server/test/scale-testing.js
=> Implement scale testing for LTI POST requests

client/src/inside/components/mar/mar-helper.js, client/src/inside/components/mar/mar-today.js, client/src/inside/components/page/EhrPageTable.vue
=> Fix MAR records view breaking when deleting medOrders

client/src/App.vue, client/src/helpers/auth-helper.js, client/src/helpers/store-helper.js, client/src/inside/components/EhrSpecial.vue, client/src/store/__mock__/mock-instoreHelper.js, client/src/store/modules/authStore.js, client/src/store/modules/instoreHelper.js, client/src/store/modules/visit.js
Centralize in one place and clear up the confusion around where it is and how to get it
=> Refactor the API_URL storage

client/src/inside/components/page/ehr-helper.js
=> Implement merging for formData objects when submitting edits

client/src/outside/components/ActivityListItem.vue
=> Implement a more descriptive view for courses page

.gitignore, client/src/App.vue, client/src/helpers/auth-helper.js, client/src/helpers/axios-helper.js, client/src/helpers/store-helper.js, client/src/outside/views/Admin.vue, client/src/outside/views/AdminDashboard.vue, client/src/outsideRoutes.js, client/src/store/modules/authStore.js, server/package.json, server/src/config/admin-password-sample.txt, server/src/config/admin-password.txt, server/src/helpers/admin.js, server/src/helpers/middleware.js, server/src/mcr/admin/admin-controller.js, server/src/mcr/auth/auth-controller.js, server/src/mcr/lti/lti.js, server/src/server/api.js, server/src/server/generate-password.js
Implement a JWT token system to authenticate users from the time the enter via the LMS until their session expires.
Includes starting with a "refresh token" that is provided on the incoming URL. 
This token must be validated within a minute and the client will get a new token containing their visit id.
This token is needed on non public API calls.
Also provide an Admin login screen and dashboard and API end points. The admin password is 
generated and stored on the server. Only persons authorizated to access the server can obtain this password.
Admin functions include deleting records and working with tool consumers.
=> Implement jwt token and admin login

client/src/App.vue, client/src/helpers/auth-helper.js, client/src/helpers/ehr-text.js, client/src/inside/components/page/EhrElementCheckset.vue, client/src/inside/components/page/ehr-helper.js, client/src/outside/components/ClassList.vue, client/src/outside/views/Admin.vue, client/src/outside/views/AdminDashboard.vue, client/src/store/modules/activityDataStore.js, client/src/store/modules/activityStore.js, client/src/store/modules/assignmentListStore.js, client/src/store/modules/assignmentStore.js, client/src/store/modules/consumerListStore.js, client/src/store/modules/consumerStore.js, client/src/store/modules/userStore.js, server/src/config/text.js, server/src/helpers/middleware.js, server/src/mcr/activity/activity-controller.js, server/src/mcr/admin/admin-controller.js, server/src/mcr/auth/auth-controller.js, server/src/mcr/common/base.js, server/src/mcr/lookahead/lookahead-controller.js, server/src/server/app.js
=> Improve error message management

server/src/helpers/middleware.js, server/src/mcr/common/base.js, server/src/mcr/consumer/consumer-controller.js, server/src/server/api.js
=> Implement admin middleware for delete, toolConsumer creation and admin end points

client/src/app/ui/UiButton.vue, client/src/app/ui/UiConfirm.vue, client/src/helpers/auth-helper.js, client/src/helpers/store-helper.js, client/src/main.js, client/src/outside/components/AssignmentsListing.vue, client/src/store/modules/assignmentStore.js, client/src/store/modules/authStore.js, client/src/store/modules/instoreHelper.js, server/src/mcr/assignment/assignment-controller.js, server/src/mcr/auth/auth-controller.js, server/src/server/api.js
=> Allow admin to delete unneeded assignments

server/src/mcr/assignment/assignment.js
=> Make compound unique index for toolConsumer and externalId

client/src/helpers/store-helper.js, client/src/store/modules/authStore.js
=> Set apiUrl and authToken to localStorage, enabling the session to be extended to other tabs

server/src/helpers/middleware.js, server/src/mcr/auth/auth-controller.js, server/src/mcr/lti/lti.js, server/src/mcr/playground/playground-controller.js, server/src/server/api.js, server/test/scale-testing.js
Works towards scale-testing and postman testing
=> Improve the way HMAC-SHA1 is signed and auth'd, as well enhancements on the Postman test logic

client/src/app/components/AppDialogShell.vue, client/src/helpers/ehr-types.js, client/src/helpers/ehr-utils.js, client/src/inside/components/page/ehr-helper.js, client/src/inside/components/page/ehr-validations.js, client/src/inside/defs-grid/current-visit-1.js, client/src/inside/defs-grid/current-visit-2.js, client/src/inside/defs-grid/external-resources.js, client/src/inside/defs-grid/patient-chart.js, client/src/inside/defs-grid/patient-profile.js, client/src/inside/defs-grid/test-page.js, client/src/store/__mock__/mock-instoreHelper.js, makeEhrV2/gen_defs/ehr-short-forms.js, makeEhrV2/hashMapFile.json, makeEhrV2/raw_data/current-visit-2.txt
This PR merges in Vinicius' work in PR 616.
Reused the 24 hr time validation used in the ehr-utils.
Fix the regular expression.
Apply the time24 validation to the table record header time field.
Clean up some lint errors.
=> Time validation on PRN and table form headers

client/public/index.html, client/src/app/components/AppHeader.vue, client/src/helpers/store-helper.js, client/src/outside/components/ActivityListItem.vue, client/src/outside/components/ClassList.vue, client/src/store/modules/classListStore.js
Course listing fixed:
- app title and course activity title
- activity list show correct class list stats
Update application header bar with clearer text.
Update layout of Class List page to reduce clutter.
=> Update app banner, course listing and class list

deployment/package.json, package.json
=> Add npm scripts to update prod on one line

LICENSE, LICENSE-addition.txt, package.json
The license change was only meant for the bccampus master branch
=> Undo previous committ

client/src/App.vue, client/src/helpers/auth-helper.js, client/src/helpers/ehr-text.js, server/src/config/text.js
=> Fix App.vue loading errors

client/src/App.vue, client/src/helpers/store-helper.js, client/src/outside/components/ActivityListItem.vue, client/src/outside/components/AssignmentsListing.vue, client/src/outside/components/ClassList.vue, server/src/helpers/middleware.js
Need to load App before components so the authorization is in place.
Clean up debug tracing messages and flags to enable disable.
=> Fix loading race condition and auth token

client/src/app/components/SystemMessage.vue, client/src/helpers/auth-helper.js, server/package.json, server/src/config/config.js, server/src/helpers/admin.js, server/src/helpers/middleware.js, server/src/mcr/activity-data/activityData.spec.js, server/src/mcr/admin/admin-controller.js, server/src/mcr/admin/admin-controller.spec.js, server/src/mcr/admin/admin-server.spec.js, server/src/mcr/assignment/assignment.server.spec.js, server/src/mcr/auth/auth-controller.js, server/src/mcr/auth/auth-controller.server.spec.js, server/src/mcr/auth/auth-controller.spec.js, server/src/mcr/common/auth-util.js, server/src/mcr/common/auth-util.spec.js, server/src/mcr/common/test-helper.js, server/src/mcr/consumer/consumer.spec.js, server/src/mcr/feedback/feedback.server.spec.js, server/src/mcr/lookahead/lookaheadController.spec.js, server/src/mcr/lti/lti.js, server/src/mcr/lti/lti.spec.js, server/src/mcr/seed/seedData.server.spec.js, server/src/server/api.js, server/src/server/server.spec.js
This PR aggregates what has been done in other PRs by not only implementing the backend test enhancements which has been addressed in #705, as well as it implements the refactoring of the auth flow (#712). It also adds more coverage to the auth flow by testing the newly created helper class (AuthUtil) as well as enhancing the admin and auth tests.
=> Improve Backend tests, refactor auth / admin flow and improve its test coverage

client/src/app/components/AppHeader.vue, client/src/icons.js, client/src/inside/layout/LayoutEhr.vue, client/src/scss/styles.scss
=> Create tablet view for instructor and student pages

client/src/inside/components/mar/mar-today.js, client/src/inside/components/mar/med-order.js, client/src/inside/defs-grid/current-visit-2.js, makeEhrV2/hashMapFile.json, makeEhrV2/raw_data/current-visit-2.txt
=> Implement OD medications in Medication and MARs pages

client/src/helpers/page-controller.js
See https://github.com/BCcampus/edehr/issues/730
=> Reload each EHR page

client/src/app/components/SystemMessage.vue, client/src/helpers/ehr-actions.js, client/src/helpers/ehr-text.js, client/src/inside/components/EhrNavPanelAction.vue
=> Show message banner when Activity has been closed for the student

client/src/inside/layout/LayoutEhr.vue
=> Fix mobile navigation

.github/workflows/main.yml
=> Begin implementation of main.yml for github actions

client/package-lock.json, client/package.json, client/src/app/components/AppDialogShell.vue, client/src/helpers/directives-filters.js, client/src/helpers/test/ClassList.spec.js, client/src/helpers/test/__snapshots__/ClassList.spec.js.snap, client/src/main.js, client/src/outside/components/ClassList.vue
Move directive and filter settings on main Vue instance into a helper so it can be shared with unit tests.
Add data test ids to html elements to assist with testing.
Add script to package.json to update snapshots
Fix and augment the ClassList tests.
=> Client side tests

server/src/mcr/auth/auth-controller.server.spec.js
This was mostly addressed on #717.
Closes #719
=> Improve logging in auth-controller test

server/src/mcr/demo/demo.server.spec.js, server/src/mcr/demo/demo.spec.js
=> Refactor demo testing to reflect latest changes

client/src/helpers/page-controller.js, client/src/helpers/store-helper.js, client/src/outside/components/ClassList.vue
for both student and instructor and demo users refactor the complex page load code to use async/await. Next step use this cleaner approach and  get rid of wasteful API calls that slow down the app.
refactor loading.
Note several new issues have been added to github. These defects existed before this refactoring. They need fixing as soon as possible.
=> refactor page loading

client/src/outside/components/DemoAccess.vue
use the login text not the logout text
=> fix log in dialog

client/src/inside/components/page/ehr-helper.js
=> Fix trim() error on ehr-helper

client/src/helpers/test/ehr-actions.spec.js, client/src/helpers/test/store-helper.spec.js, client/src/helpers/test/testHelper.js
=> Implement ehr-actions test coverage

client/src/helpers/test/ehr-defs-grid.spec.js
=> Improve ehr-defs-grid coverage

client/src/helpers/test/MockFile.js, client/src/helpers/test/ehr-utils.spec.js, client/src/helpers/test/mockData.json, client/src/helpers/test/testHelper.js
=> Implement tests for ehr-utils

client/src/helpers/test/ehr-text.spec.js
=> Implement ehr-text test coverage

client/src/helpers/eval-helper.js, client/src/helpers/test/ehr-types.spec.js, client/src/helpers/test/eval-helper.spec.js
=> Implement eval-helper and ehr-types test coverage

client/src/helpers/axios-helper.js, client/src/helpers/test/axios-helper.spec.js
=> Implement axios-helper test coverage

client/src/helpers/auth-helper.js, client/src/helpers/demo-helper.js, client/src/helpers/test/auth-helper.spec.js, client/src/helpers/test/demo-helper.spec.js, client/src/helpers/test/testHelper.js, client/src/store/modules/authStore.js, client/src/store/modules/demoStore.js
=> Implement auth and demo helpers test coverage

client/src/helpers/ehr-utils.js, client/src/helpers/test/ehr-utils.spec.js, client/src/inside/components/page/ehr-helper.js, client/src/inside/components/page/ehr-validations.js, client/src/inside/components/page/test/ehr-validator.spec.js, client/src/inside/defs-grid/current-visit-2.js, makeEhrV2/hashMapFile.json, makeEhrV2/raw_data/current-visit-2.txt
Add a new validation function: range, to be used to validate the wound bed calculation. This is calculated as the sum of other fields but we certainly don't want to allow a % total to be greater than 100.
Along with the new function added unit tests on the ehr validation methods.
Import latest INPUTs changes based on input from SMEs
=> EHR wound page content, range validation

client/src/helpers/page-controller.js, client/src/helpers/test/axios-mock-helper.js, client/src/helpers/test/page-controller.spec.js, client/src/helpers/test/store-helper.spec.js, client/src/helpers/test/testHelper.js
=> Implement page-controller tests

client/src/inside/defs-grid/current-visit-2.js, makeEhrV2/hashMapFile.json, makeEhrV2/package.json, makeEhrV2/raw_data/current-visit-2.txt
Update the generator sub-project via npm update.
=> Update Inputs with more wound content from SMEs

client/src/helpers/case-context.js, client/src/helpers/ehr-defs-grid.js, client/src/helpers/store-helper.js, client/src/helpers/test/case-context.spec.js, client/src/helpers/test/ehr-defs-grid.spec.js, client/src/helpers/test/mockData.json, client/src/helpers/test/store-helper.spec.js, client/src/inside/components/page/EhrDialogForm.vue, client/src/inside/components/page/EhrElementCommon.vue, client/src/inside/layout/LayoutEhr.vue, client/src/store/index.js, client/src/store/modules/assignmentStore.js, client/src/store/modules/system.js, makeEhrV2/gen_defs/input-to-def.js
Check box controls flag. State persists for user across page refresh and leaving and returning to app.
=> #810 Case Context feature flag

client/src/helpers/case-context.js, client/src/helpers/test/case-context.spec.js, client/src/inside/components/page/EhrDialogForm.vue, client/src/inside/components/page/EhrElementCommon.vue, client/src/inside/layout/LayoutEhr.vue, client/src/store/modules/assignmentStore.js
=> Fix record header defects

client/src/helpers/ehr-defs-grid.js, client/src/helpers/ehr-types.js, client/src/helpers/test/page-defs.spec.js, client/src/inside/defs-grid/index.js
=> Implement page-def tests

client/src/app/components/AppHeader.vue
=> Change parent class scope to AppHeader's ui-confirm dialog

server/src/mcr/demo/assignment-defs.js
https://github.com/BCcampus/edehr/issues/820
=> Fix #820 demo mode startup is broken

client/src/inside/components/chart/VitalsChart.vue
=> Limit scale for ipad vital-sign-graph

server/src/mcr/lti/lti.js
lti assignment creation issue fixed.
=> lti assignment creation issue fixed.

server/src/mcr/files/files-controller.js, server/src/mcr/files/files-controller.spec.js
Extend the unit tests to cover more  code branches.
Extract text that the user sees into a central location within with the files controllers. Prepares for review by UI.
=> File Upload server

client/src/inside/components/mar/med-order.js, client/src/inside/components/mar/tests/med-order.spec.js
=> Implement tests for med-order

client/src/inside/components/mar/mar-today.js, client/src/inside/components/mar/med-order.js, client/src/inside/components/mar/tests/mar-today.spec.js
Closes #835
Works towards #806
=> Implement mar-today tests

client/src/inside/components/mar/tests/mar-summary.spec.js
=> Begin implementation of mar-summary tests

client/src/inside/components/mar/mar-today.js, client/src/inside/components/mar/med-order.js, client/src/inside/components/mar/tests/mar-today.spec.js, client/src/inside/components/mar/tests/med-order.spec.js
=> Improve tests upon comments 

client/src/inside/components/mar/tests/mar-entity.spec.js, client/src/inside/components/mar/tests/mar-summary.spec.js, client/src/inside/components/mar/tests/mar-test-helper.js, client/src/inside/components/mar/tests/mar-today.spec.js, client/src/inside/components/mar/tests/marMock.json, client/src/inside/components/mar/tests/med-order.spec.js
=> Improve mar-tests, create helper functions and move mockData to a JSON file

client/src/helpers/test/testHelper.js, client/src/inside/components/page/ehr-helper.js, client/src/inside/components/page/test/ehr-helper.spec.js
=> Create ehr-helper tests

client/src/app/components/AppDialogShell.vue, client/src/app/components/AppHeader.vue, client/src/inside/components/EhrNavListItem.vue, client/src/inside/layout/LayoutEhr.vue
=> Improve iPhone mobile design

client/src/inside/components/page/EhrElementCommon.vue
=> Remove legacy fallback value call to EhrDefs

client/src/app/ui/UiButton.vue, client/src/inside/components/mar/MarTodayContent.vue, client/src/outside/components/ClassList.vue, client/src/outside/components/EhrSeedDataList.vue, client/src/scss/_definitions.scss, client/src/scss/styles.scss, client/src/scss/styles/_buttons.scss, client/src/scss/styles/_forms.scss, client/src/scss/styles/_tables.scss, client/src/scss/styles/_typography.scss
remove lots of unused css classess
standardize button styling to apply to all buttons in the app not just the UiButton component.
=> CSS clean up

client/src/inside/components/mar/tests/mar-helper.spec.js, client/src/inside/components/mar/tests/mar-test-helper.js, client/src/inside/components/mar/tests/marMock.json
=> Implement mar-helper tests

client/src/inside/components/mar/tests/mar-summary.spec.js, client/src/inside/components/mar/tests/mar-test-helper.js
=> Implement summaryRefresh test on mar-summary

client/src/helpers/store-helper.js, client/src/store/modules/seedListStore.js
=> Improve seedId persistance fixing page refreshing on NavPanel

client/src/helpers/case-context.js, client/src/helpers/test/case-context.spec.js, client/src/inside/components/page/EhrDialogForm.vue, client/src/inside/components/page/EhrElementCommon.vue, makeEhrV2/gen_defs/input-to-def.js
Pull Vinicius' PR and resolve conflicts
=> Resolve conflicts

client/src/inside/components/EhrFileLink.vue, client/src/inside/components/page/EhrElementFile.vue, client/src/inside/components/page/EhrPageTable.vue, client/src/inside/components/page/EhrTableElement.vue, client/src/outside/components/FileList.vue, client/src/outside/components/FileSelectDialog.vue, client/src/store/modules/fileListStore.js
Create a component to display a EhrFile whether that's in the file listing, the upload dialog, the file select dialog or in the EHR.
Have option to make this a clickable link.
Later, add ability to retrieve a thumbnail and link to full image.
Later, have a hover or other action to show a larger image without needing to open in a new tab.
=> Create a EHR File Link component

client/src/helpers/test/testHelper.js, client/src/outside/components/Activity.vue, client/src/outside/components/ClassList.vue, client/src/outside/views/Users.vue, client/src/outsideRoutes.js, makeEhrV2/raw_data/outsideDefs.json, server/src/config/config.js, server/src/mcr/activity/activity-controller.js, server/src/mcr/common/test-helper.js, server/src/mcr/demo/demo.server.spec.js, server/src/mcr/lti/lti.js, server/src/mcr/user/user.js, server/src/mcr/visit/visit.js, server/src/server/api.js, server/test/scale-testing.js
Remove dependance on users email address and replace with the user's LMS id. 
Fix demo unit test
=> User privacy

.gitignore, client/package.json, client/public/index.html, client/sample.env, client/src/App.vue
Change the site name, as seen in the browser tab, based on .env
VUE_APP_SITE_TITLE=Some Title
add publish step to client build
add sample .env file
=> Set Site Title based on .env

README.md, client/src/app/components/AppHeader.vue, client/src/appText.js, client/src/helpers/demo-helper.js, client/src/helpers/demo-store-helper.js, client/src/helpers/page-controller.js, client/src/outside/components/PageNotFound.vue, client/src/outside/views/Help.vue, client/src/store/modules/demoStore.js, server/package.json, server/src/config/config.js, server/src/mcr/files/files-controller.js, server/src/mcr/lti/lti.js, server/src/mcr/metric/metric-controller.js, server/src/server/api.js
Seeking cause for some occasional problems with demo mode and how it resolves the ehr page.
LTI Clean up the code. Add some documentation. Remove the apiUrl parameter in the LTI request because it is not used.
Improve and fix issues with demo exit
Add system details to Help.vue (/about) to indicate API version and API runtime etc.
Fix how server cleans up when a user exits the demo mode (local storage had stuff left behind and the removal of the files directory sometimes failed)
Metrics don't track last url if it was call to metric
=> Add system info to about page

deployment/package.json, server/package.json, server/src/config/config.js, server/src/mcr/consumer/consumer-controller.js, server/src/mcr/demo/demo-controller.js, server/src/mcr/files/files-controller.js, server/src/server/api.js
Needed to remove the files and other dependants before removing the tool consumer.
Fix issue with configuration. Need to have the scheme for the demo controller to logout.
Remove console out in CORs handler
=> Fix issues with exiting demo mode

client/src/App.vue, client/src/app/components/AppFooter.vue, client/src/helpers/ehr-utils.js, client/src/helpers/page-controller.js, client/src/helpers/store-helper.js, client/src/inside/layout/LayoutEhr.vue, client/src/outside/layout/LayoutOutside.vue, client/src/outside/views/Help.vue, client/src/store/modules/system.js, deployment/d-c.yml, deployment/sample.env.site, edehr.org/env/sample.env, edehr.org/tmp, edehr.org/user_edehr_setup.sh, package-lock.json, package.json, server/package.json, server/src/config/config.js, server/src/server/api.js
Includes application version and site title.
Display app ver in footer
Use site title as document title.
Set app title from env and via api
=> ApiData - client gets key data from api on load

client/src/app/components/AppDialogShell.vue, client/src/directives/drag-directive.js
The touch events needed to be used properly
=> Fix dialog move on mobile devices

client/src/app/components/AppFooter.vue, client/src/app/components/AppHeader.vue, client/src/app/components/AppQuote.vue, client/src/app/components/AppRef.vue, client/src/app/components/AppSourceList.vue, client/src/app/components/AppTextWithRefs.vue, client/src/app/edehr-org/EdEhrOrg.vue, client/src/app/edehr-org/EdEhrOrgFooter.vue, client/src/app/edehr-org/ed-ehr-org.js, client/src/appText.js, client/src/directives/text-to-html.js, client/src/helpers/store-helper.js, client/src/outside/components/DemoAccess.vue, client/src/outside/views/About.vue, client/src/outside/views/Help.vue, client/src/outside/views/Home.vue, client/src/outside/views/Terms.vue, client/src/outside/views/terms-and-conditions.md, client/src/outsideRoutes.js, client/src/scss/styles.scss, client/src/scss/styles/_sections.scss, client/src/scss/styles/_typography.scss, makeEhrV2/raw_data/outsideDefs.json
Rewrite about page with more details about history of EdEHR
Plus edehr.org content including:
Terms and Conditions and edehr.org content
Add mailto link conversion in the text to html directive
=> About page text

client/src/inside/components/page/EhrElementCommon.vue, client/src/inside/components/page/EhrTableStacked.vue
TypeError _loadPageData(src/inside/components/page/ehr-helper)
New Issue
Cannot read properties of undefined (reading 'length')
=> Work towards resolving a sentry reported issue

client/src/inside/components/page/EhrElementSimTime.vue, client/src/store/modules/ehrDataStore.js
TypeError
Cannot read properties of undefined (reading 'visitDay')
webpack://edehr-client/src/inside/components/page/EhrElementSimTime.vue in call at line 79:1
=> Tracing Sentry reported issue

client/src/app/ui/UiInfo.vue, client/src/helpers/ehr-utils.js, client/src/inside/components/page/EhrElementCommon.vue, client/src/inside/components/page/EhrElementForm.vue, client/src/inside/components/page/EhrElementSimTime.vue, client/src/inside/components/page/EhrPageFormLabel.vue, client/src/inside/components/page/ehr-calcs.js, client/src/inside/components/page/ehr-helper.js, client/src/inside/defs-grid/ehr-page-defs.js, client/src/main.js, client/src/scss/styles/_forms.scss, client/src/store/modules/ehrDataStore.js, makeEhrV2/gen_defs/helps.js, makeEhrV2/generated/ehrDefs/ehr-page-defs.js, makeEhrV2/hashMapFile.json, makeEhrV2/raw_data/current-visit-2.txt, makeEhrV2/raw_data/patient-chart.txt, package-lock.json, package.json, server/src/ehr-definitions/ehr-page-defs.js
Define a new EHR calculation type 'wbcAbs' that multiplies the WBC from the embedded CBC analysis against a relative WBC differential value.
Can now extract values from a row from an embedded table.
Adjust layout of EHR forms, rearrange some forms, 
Resolve sentry issue
Fix issue with missing seed meta data.
STOP Sentry on local host client
=> Hematology WBC differential absolute calculations

server/package.json, server/src/mcr/metric/metric-controller.js, server/src/mcr/metric/monitor.js, server/src/mcr/metric/system.js, server/src/server/api.js, server/src/server/trace-api.js
Add cpu and mem data to monitoring
Consider using pressure
See https://lwn.net/Articles/759781/
=> Server side monitoring

client/src/helpers/axios-helper.js, client/src/helpers/page-controller.js, client/src/outside/components/lms-activity/StudentEvalControl.vue, client/src/outside/views/ClassList.vue, client/src/store/modules/instructor.js, server/src/helpers/middleware.js, server/src/mcr/admin/admin-controller.js, server/src/mcr/common/auth-util.js, server/src/mcr/lti/lti.js
Repair some issues with how the current student index is managed, class lists are sorted, and which seed is being edited.
=> seed editing and student evaluation

client/src/outside/components/seed-struct/SeedPage.vue, client/src/store/modules/system.js
Instructors asked to keep their preference across pages and sessions
=> Keep the user's setting for table orientation in the condensed view

client/src/app/components/AppFooter.vue, client/src/helpers/store-helper.js, client/src/inside/components/page/EhrElementCommon.vue, client/src/inside/components/page/EhrTableCommon.vue, client/src/inside/components/page/EhrTableStacked.vue, client/src/inside/components/page/EhrTableVertical.vue, client/src/outside/components/learning-object/LearningObjectDialog.vue, client/src/outside/views/SeedView.vue, client/src/store/modules/ehrDataStore.js
Move the 'hidden' button that throws an error to test Sentry to the admin pages
remove db stmts
=> Fix change case study on learning object page not refreshing in display

client/src/ehr-definitions/EhrDataModel.js, client/src/ehr-definitions/ehr-data-model-utils.js, client/src/ehr-definitions/ehr-page-defs.js, client/src/inside/components/page/EhrTableCommon.vue, ehr-workspace/src/ehr-definitions/EhrDataModel.js, ehr-workspace/src/ehr-definitions/ehr-data-model-utils.js, ehr-workspace/src/ehr-definitions/ehr-page-defs.js, ehr-workspace/src/ehr-tests/ev2_1_1.spec.js, ehr-workspace/src/resources/ev2_1_1_input.json, makeEhrV2/generated/ehrDefs/ehr-page-defs.js, makeEhrV2/hashMapFile.json, makeEhrV2/raw_data/current-visit-2.txt, server/src/ehr-definitions/EhrDataModel.js, server/src/ehr-definitions/ehr-data-model-utils.js, server/src/ehr-definitions/ehr-page-defs.js, server/src/mcr/assignment/assignment.system.spec.js
https://github.com/edehr/edehr/issues/1031
=> Issue 1031; Med route nebulized & topical; change Inhalation to Inhaler

client/src/ehr-definitions/common-utils.js, client/src/helpers/ehr-utils.js, client/src/helpers/test/ehr-utils.spec.js, client/src/inside/components/mar/MarTabs.vue, client/src/inside/components/page/EhrPageFormLabel.vue, client/src/inside/components/page/EhrTableVertical.vue, client/src/outside/components/seed-management/SeedDelete.vue, client/src/outside/components/seed-management/SeedListItem.vue, client/src/outside/components/seed-struct/SeedTableHoriz.vue, client/src/outside/components/seed-struct/SeedTableVert.vue, client/src/outside/views/SeedView.vue, client/src/scss/styles/_tables.scss, ehr-workspace/src/ehr-definitions/common-utils.js, ehr-workspace/src/ehr-tests/common-utils.spec.js, server/src/ehr-definitions/common-utils.js, server/src/mcr/activity-data/activity-data-controller.js, server/src/mcr/seed/seedData-controller.js, server/src/server/trace-ehr.js
Fix validation of recHdr day when value is 0
Seed condensed, skip rowId, put tableCss on the cell and not table cell
With the css on the table cell if affects the cell contents. When the cell is a rowId and the css is to hide that it was hiding the view button.
Put current version of Mar first (v1) until v2 is ready for use
Add warning that v2 MAR is under construction
avoid mandatory styling in elements in embedded forms
Seed delete - reviewed and fixed; Ehr trace include toolConsumer
=> Refinements

client/src/ehr-definitions/ehr-def-utils.js, client/src/ehr-definitions/ehr-select.js, client/src/inside/components/EhrFileLink.vue, client/src/inside/components/mar/med-order.js, client/src/inside/components/page/EhrElementCheckset.vue, client/src/inside/components/page/EhrElementCommon.vue, client/src/inside/components/page/EhrElementForm.vue, client/src/inside/components/page/EhrElementSelect.vue, client/src/inside/components/page/EhrPageTable.vue, client/src/outside/components/seed-struct/SeedTableHoriz.vue, client/src/outside/components/seed-struct/SeedTableVert.vue, ehr-workspace/src/ehr-definitions/ehr-def-utils.js, ehr-workspace/src/ehr-definitions/ehr-select.js, ehr-workspace/src/ehr-tests/ehr-def-utils.spec.js, server/src/ehr-definitions/ehr-def-utils.js, server/src/ehr-definitions/ehr-select.js, server/src/mcr/files/files-controller.js, server/src/mcr/metric/monitor.js
Fix file download to save file with file name and not consumer id.
Adjust monitor api to return counts rather than elapsedMs
EHR select values human readable; Med schedule options DRY
Med schedule times does not need the spaces in the array.
=> Fix file download to save file with fileName not consumerId

server/src/db/dbSeeder.js
The EHR models were getting updated twice.
=> Only do model updates once on start up

client/src/ehr-definitions/ehr-data-model-utils.js, client/src/ehr-definitions/ehr-page-defs.js, client/src/inside/components/chart/VitalsChart.vue, client/src/inside/components/chart/vitalChart.js, client/src/inside/components/chart/vitalModel.js, client/src/inside/components/mar/MarTabs.vue, client/src/inside/components/page/ehr-data.js, ehr-workspace/src/ehr-definitions/ehr-data-model-utils.js, ehr-workspace/src/ehr-definitions/ehr-page-defs.js, makeEhrV2/generated/ehrDefs/ehr-page-defs.js, makeEhrV2/hashMapFile.json, makeEhrV2/raw_data/current-visit-3.txt, server/checkNodeVersion.js, server/package.json, server/src/ehr-definitions/ehr-data-model-utils.js, server/src/ehr-definitions/ehr-page-defs.js, server/src/mcr/common/test-helper.js, server/src/mcr/metric/system.js, server/src/mcr/roles/roles.js, server/src/mcr/roles/roles.system.spec.js, server/src/mcr/user/user-controller.js, server/src/mcr/visit/visit-controller.js, server/src/mcr/visit/visit.js
Add Hemoglobin to lab request
Vitals charting nuance the display of blood pressure
Mar page - remove "v2"
Restore table sort by day/time
LTI. Role. Remove unused roles because they cause problems.
The Role class had an isAdmin and isDeveloper role. Neither are used but both were used in the logic to validate a request. 
If a user is the Admin of a Moodle instance and they change their role to student then the LTI request resulted in an invalid role. (Moodle sends a message without a student or instructor role but with a admin role and that caused problems.
Server side - check node version before building the server subproject
System metrics -- add more details about the cp usage
=> MAR, Vitals, Lab Req, table sort, tech debt

client/src/outside/components/seed-management/SeedActions.vue, client/src/outside/components/seed-management/SeedMngPage.vue, client/src/outside/views/SeedList.vue, client/src/outside/views/SeedView.vue, client/src/scss/_definitions.scss, client/src/scss/styles/_apptags.scss, client/src/scss/styles/_buttons.scss
Change styling of LIS app, a button in the seed editing view and clean up the page change urls for seed editors
=> Minor tweaks

server/src/db/dbSeeder.js, server/src/mcr/demo/demo-controller.js, server/src/server/api.js
Removes all full demo sandboxes that are older than 2023-09-01
Have three ways to query for old demos
=> On startup clean out all old demo consumer spaces

server/package.json, server/src/helpers/middleware.js, server/src/mcr/lti/lti.js, server/src/server/trace-api.js
Enable tracing on prods
This will help so much to check on server status. Currently to see what is happening the admin needs to tail a log file that changes name every hour.
=> Api tracing - add essential details

client/src/outside/components/lms-activity/ActivityActions.vue, client/src/outside/views/ClassList.vue
Disable the download button
Provide a default empty class list for the v-for
=> On Instructor class list page without any class list

client/src/app/components/AppHeaderDocumentationMenu.vue, client/src/app/components/AppHeaderMenu.vue, client/src/appText.js, client/src/ehr-definitions/ehr-page-defs.js, client/src/helpers/responsive.js, client/src/helpers/store-helper.js, client/src/inside/components/page/EhrElementForm.vue, client/src/inside/components/page/EhrPageTable.vue, client/src/inside/components/page/EhrTableVertical.vue, client/src/inside/components/page/ehr-helper.js, client/src/inside/components/page/ehr-table-actions.js, client/src/inside/layout/LayoutEhr.vue, client/src/outside/components/learning-object/LearningObjectDialog.vue, client/src/outside/views/DemoCourse.vue, client/src/scss/styles/_forms.scss, client/src/scss/styles/_tables.scss, client/src/store/modules/assignmentStore.js, ehr-workspace/src/ehr-definitions/ehr-page-defs.js, makeEhrV2/gen_defs/helps.js, makeEhrV2/generated/ehrDefs/ehr-page-defs.js, makeEhrV2/hashMapFile.json, makeEhrV2/raw_data/med-lab.txt, server/src/ehr-definitions/ehr-page-defs.js, server/src/mcr/assignment/assignment-controller.js, server/src/server/trace-api.js
Hematology - WBC morphology layout
Fix some responsive issues, especially with main hamburger menu
Demo course page --- fix responsiveness and text to suit
App top bar - fix responsiveness
Content creators can now set lobj to use or not use a case study
Allow many draft rows; Lab ref ranges for lab_results
=> LObj without seed is possible. Many draft rows. Responsive fixes. Hematology.

client/src/helpers/mPatientHelper.js, client/src/inside/components/EhrPatientTab.vue, client/src/scss/styles/_forms.scss, client/src/scss/styles/_mpatient.scss, client/src/store/modules/mPatientStore.js, client/src/store/modules/seedListStore.js
Prevent patient tab change when editing form
Fix layout of EHR page form.
On seed change add direct lateral push of new data to mPatientStore's copy
=> Update patient tab on edit of family name

client/src/inside/components/page/EhrPageTable.vue, client/src/inside/components/page/EhrTableCommon.vue, client/src/inside/components/page/EhrTableStacked.vue, client/src/inside/components/page/EhrTableVertical.vue, client/src/inside/components/page/ehr-helper.js, client/src/inside/components/page/ehr-table-draft.js, client/src/outside/views/Course.vue
This has been something we've all wanted since the beginning of the project.
=> Allow content editors to edit rows in tables!!!

client/src/outside/components/seed-management/SeedSelectComponent.vue, client/src/outside/views/LearningObjects.vue, server/package.json, server/src/mcr/assignment/assignment-controller.js, server/src/mcr/assignment/assignment.js, server/src/mcr/common/assignment-defs.js, server/src/mcr/common/counter-controller.js, server/src/mcr/common/counters.js, server/src/mcr/common/counters.spec.js, server/src/mcr/demo/demo-controller.js, server/src/resources/BonlanleAkosua_after.json, server/src/resources/BonlanleAkosua_before.json, server/src/resources/lobj_erToothPainManagement.json, server/src/resources/seeds/CorserRodger3140005.json, server/src/resources/seeds/HarveyRosalie3140002.json, server/src/resources/seeds/HyettWayne3140004.json, server/src/resources/seeds/McGahanAnna3140006.json, server/src/resources/seeds/MitchelLou-3140003.json, server/src/resources/seeds/PowerHarry3140001.json, server/src/resources/seeds/WilliamsPaul3140007.json
Namespace LObj sequence generator to the tool consumer
Fix the LObj use of mPatientAppType when there is no seed
=> Add more case studies and toothPain activity to demo

client/src/app/components/AppDialogShell.vue, client/src/app/ui/UiInfo.vue, client/src/inside/components/EhrContextStudent.vue, client/src/inside/components/page/EhrTableStacked.vue, client/src/scss/styles.scss
=> instructor feedback in optional dialog

client/src/ehr-definitions/ehr-models.js, client/src/ehr-definitions/ehr-page-defs.js, client/src/helpers/demo-helper.js, client/src/helpers/page-controller.js, client/src/helpers/web-socket-client.js, client/src/inside/components/mar/MarTabs.vue, client/src/inside/components/marV2/MarBarcodeDialog.vue, client/src/inside/components/page/EhrDialogForm.vue, client/src/inside/components/page/EhrPageForm.vue, client/src/inside/layout/LayoutEhr.vue, client/src/outside/components/seed-struct/SeedFormElement.vue, client/src/outside/components/seed-struct/SeedPages.vue, client/src/outside/components/seed-struct/SeedStructural.vue, client/src/outside/components/seed-struct/SeedTableHoriz.vue, client/src/outside/components/seed-struct/SeedTableVert.vue, client/src/outside/layout/LayoutLms.vue, client/src/outside/views/LmsInstructorActivity.vue, client/src/store/modules/system.js, ehr-workspace/src/ehr-definitions/ehr-models.js, ehr-workspace/src/ehr-definitions/ehr-page-defs.js, nginx/site/api.inc, server/src/ehr-definitions/ehr-models.js, server/src/ehr-definitions/ehr-page-defs.js, server/src/mcr/consumer/consumer-controller.js, server/src/mcr/course/course.js, server/src/server/app.js
* indicates a change that the user may notice
EHR side
* Add validation to all visit day and time inputs. Visit admission day. Gastrointestinal NPO day. Genitourinary last change day. Biopsychosocial restraint day. Referrals appointment. Lab requisition date required.  Med admin recorded event date. Discharge summayr date. Integumentary post op day
* MAR - change the beep sounds.
* MAR - removed the confusing reset button beside the bar code button. This reset only removed the checks beside the meds. It's just easier for the user to click the medication.
* Fix edit cancel (delete) of a row in the patient location table. This table lacks a rec header, which is something to fix someday.
Spinner created an error messages about lacking a reference. Pull the spinner out of the div that will …
=> many details. see below

client/src/ehr-definitions/ehr-page-defs.js, ehr-workspace/src/ehr-definitions/ehr-page-defs.js, server/src/ehr-definitions/ehr-page-defs.js
Do not perform any updates. Let content editors make updates if they desire.
=> Add record header to visit location table

client/src/helpers/date-helper.js, client/src/helpers/page-controller.js, client/src/inside/components/EhrSimulationTimeControl.vue, client/src/inside/components/page/EhrElementCommon.vue
Will need this to manage time once activities start to control time
=> Place the sim day and time accessors in a central place
