client/src/helpers/ehr-helper.js
client/src/inside/components/EhrPageTable.vue
client/src/inside/components/mar/MarRecord.vue
client/src/inside/components/mar/MarTodayContent.vue
client/src/inside/components/mar/MedList.vue
client/src/inside/components/mar/mar-entity.js
client/src/inside/components/mar/mar-util.js
client/src/inside/components/mar/medOrder-entity.js
client/src/inside/components/mar/period-defs.js

Change EhrHelper to always recal as loaded data. There was no need try to use the cached value and the cached value did not work across the med list and mar pages.
Fix layout and composition of medication lists.

MAR display issues

---

client/src/inside/components/EhrDialogFormElement.vue
client/src/inside/components/EhrPageForm.vue
client/src/inside/components/EhrPageFormElement.vue
client/src/inside/components/EhrPageTable.vue
client/src/inside/components/Vitals.vue
client/src/scss/styles/_forms.scss

datepicker - properly disabled, can edit date as text, can delete an existing date, display the element label in the header of the calendar.
Vitals: reorganize the tabs
PageForm and Table elements now have a class for styling these top level elements.

Datepicker, Vitals, Page elements

---

client/src/inside/components/mar/MarSummary.vue
client/src/inside/components/mar/mar-entity.js
client/src/inside/components/mar/mar-helper.js
client/src/inside/components/mar/mar-summary.js
client/src/inside/components/mar/med-entity.js

When reading data back into the objects be sure to detect when the incoming object is a previous internal _data object.
Place a vertical bar in the summary table between days

MAR - fix data storage, visual day break in summary

---

client/src/helpers/store-helper.js
client/src/inside/components/EhrContextBanner.vue
client/src/inside/components/EhrContextDeveloper.vue
client/src/inside/components/page/EhrPageTable.vue
client/src/inside/components/page/EhrTableStacked.vue
client/src/inside/components/page/EhrTableVertical.vue
client/src/inside/components/page/ehr-helper.js
client/src/inside/defs-grid/current-visit-1.js
client/src/inside/defs-grid/current-visit-2.js
client/src/outside/components/ClassList.vue
makeEhrV2/gen_defs/input-to-def.js
makeEhrV2/raw_data/current-visit-1.txt

When the instructor views student data and the "develop content" flag was on the instructor would be able to edit the student's work.  Now, the action of viewing student data disables the "develop content" flag.
The seed editor now sees a developer context banner in the EHR.
Transpose tables now work. NOTE: the way to indicate a table is transposed is via the INPUTs sheet. Add 'transpose' to the 'formOptions' for the 'table_form'.  See Current Visit -1 for an example.

Table transpose, seed editor view, instructor 

---

client/src/App.vue
client/src/helpers/store-helper.js
client/src/outside/components/Activity.vue
client/src/store/modules/assignment.js

When an instructor comes to the app from Moodle the course activity they want is loaded with the class list  (and not just the first assignment) and (attempt) scroll the activity into view.
Same when the instructor clicks the assignment link in the activity they are taken to the assignment page. When the user returns to the dashboard (class list) the assignment/activity that was clicked is loaded.

Instructor dashboard -active course activity loads

---

client/src/app/components/AppDialogShell.vue
client/src/app/ui/UiButton.vue
client/src/directives/validate.js
client/src/main.js
client/src/outside/components/Activity.vue
client/src/outside/components/AssignmentsDialog.vue
client/src/outside/components/EhrSeedDataDialog.vue

Create a validate form field directive that can be applied to any form field. It will trigger when the user enters and edits or enters and then leaves (blur) the form field. Also disable the assignment dialog's save button until the form is valid.

Validate directive -- use in assignment/seed dialogs

---

client/src/inside/components/mar/MarDialog.vue

Styled the day to make it easier to see
Removed the label “medications:” as it was unneeded
Satisfies #392

Update modal form labels

---

client/src/inside/components/page/EhrElementForm.vue
client/src/inside/defs-grid/current-visit-1.js
client/src/inside/defs-grid/current-visit-2.js
client/src/inside/defs-grid/external-resources.js
client/src/inside/defs-grid/patient-chart.js
client/src/inside/defs-grid/patient-profile.js
client/src/inside/defs-grid/test-page.js
docs/developer/inside-generator/ehr-defs-input-types.md
makeEhrV2/gen_defs/helps.js
makeEhrV2/hashMapFile.json
makeEhrV2/raw_data/test-page.txt

Provide means to define a key for select options. Will use this to trigger medication scheduling visibility.
In the INPUTs sheet when defining the options for a select we can now provide key := value pairs (optional!) with the special characters of := as the separator.
sched := Scheduled
prn := PRN (as needed)
once := Once
stat := Stat
document the key value definition

Selects now have keys and values

---

client/src/outsideRoutes.js
makeEhrV2/raw_data/outsideDefs.json

Resolve problem caused whenever we generated the definitions. Previously I added two new outside routes (pages for classlist and consumers) but I declared them explicitly in the src code. Instead they should be defined in the maker raw definitions.

Outside routes

---

client/src/outside/components/EhrSeedDataList.vue

This pull request addresses limiting the number of the "Pages with Seed Data" field in the EhrSeedDataList, in order for it to display only the first one of the data, concatenated with reticences (...) so that, when hovering over the word, it would display the entire list.

Limit display of pages with seed data names

---

client/src/App.vue

Approaches this error by providing a limitation of reloads (only once) in the route watcher, located in App.vue
Closes #601

Attempt to fix slow transition of page

---

client/src/helpers/eval-helper.js
client/src/helpers/store-helper.js
client/src/inside/components/EhrContextInstructor.vue
client/src/inside/components/EhrContextStudent.vue
client/src/inside/components/EhrNavPanelAction.vue
client/src/inside/components/page/EhrPageForm.vue
client/src/inside/components/page/ehr-helper.js
client/src/main.js
client/src/outside/components/Activity.vue
client/src/outside/components/ClassList.vue
client/src/store/modules/activityStore.js
client/src/store/modules/instoreHelper.js
client/src/store/modules/instructor.js
server/src/mcr/activity/activity-controller.js
server/src/mcr/activity/activity.js

The instructor can now press a button on the class list page and close (or reopen) an activity for students. When the activity is closed the instructor can now evaluate all the student's work and not just the students who submitted.
The Class list page has also been reworked to show the instructor more information about the current state of the activity.
API change, adding in the closed property to the activity record.
Adding some data and time formatting directives into the system. These are used on the class list page.
A couple of TODO are added into the code.  
1. clean up the load class list methods to not use the filter property. 
2. See if the Activity component is still in use.  
3. See if we can remove the watch() in ClassList.vue
Student experience when activity is closed
- …

Activity can be closed

---

client/src/app/components/SystemMessage.vue

The sys message was telling the instructor that a whole class list was sent to the student if one student's work was sent.  This message is not correct and best handled, if needed, in the evaluation panel while an instructor is evaluating the student.

Remove faulty sys message for instructors

---

client/src/inside/components/page/EhrElementLookup.vue

Closes #709
The fix is done by choosing the selected value in favor of the entered input on blur. The steps are as follow:
1. When selected, set `this.selected` to the selected value, instead of only emitting the selected for the parent component.
2. On blur, verify if something has been selected and only update the value to reflect the selected one when nothing has been selected.

Bugfix: blur empties the value of selected field in order to favor entered input

---

client/src/helpers/auth-helper.js
client/src/helpers/demo-helper.js
client/src/helpers/eval-helper.js
client/src/helpers/session-keys.js
client/src/helpers/store-helper.js
client/src/helpers/test/auth-helper.spec.js
client/src/helpers/test/demo-helper.spec.js
client/src/helpers/test/ehr-utils.spec.js
client/src/helpers/test/store-helper.spec.js
client/src/inside/components/EhrContextInstructor.vue
client/src/outside/components/ClassList.vue
client/src/store/modules/activityDataStore.js
client/src/store/modules/activityStore.js
client/src/store/modules/consumerStore.js
client/src/store/modules/instructor.js

remove unused import declarations
clean up duplications with instructor get current student id
remove unused  sessionRestore (etc)
in ehr-utils use ISO 8601 data to avoid deprecation warnings in console.
in consumerStore remove session store that is not needed.
remove the redundant local getter that does nothing but call the SH.

Storage initialization cleanup

---

server/src/mcr/consumer/consumer-controller.js
server/src/mcr/visit/visit.js

removes the lti data stored in the visit record and query to get consumer drops the secret.
Closes #742

remove consumer secret from appearing in api

---

client/src/inside/components/page/ehr-helper.js

While instructors are evaluating student's work they should not to be able to edit that work.

Instructor not allowed to edit content while evaluating student work

---

client/src/app/components/AppDialogShell.vue
client/src/icons.js
client/src/inside/components/EhrNavList.vue
client/src/inside/components/EhrNavListItem.vue
client/src/inside/components/EhrNavPanel.vue
client/src/inside/components/EhrScratchPad.vue
client/src/inside/components/page/EhrPage.vue
client/src/inside/components/page/EhrPageFooter.vue
client/src/inside/components/page/EhrPageForm.vue
client/src/inside/layout/LayoutEhr.vue
client/src/scss/styles.scss

Side panel navigation
Indicator on top levels shows open/close status. helps identify which levels are top level.
Fix display of page last update section at bottom of panel.
Layout improvements
App Dialog now has cancel save buttons at top and bottom. Useful on very long forms.
Main layout adjusted to be more responsive on smaller screens

Layout and EHR side panel nav improvements 

---

client/src/helpers/store-helper.js
client/src/outside/components/learning-object/LearningObjectActions.vue
client/src/outside/components/learning-object/LearningObjectSelectItem.vue
client/src/outside/components/lms-activity/ClassListItem.vue
client/src/outside/components/lms-course/CourseActivityListItem.vue
client/src/outside/components/lms-course/CourseActivityStudentListItem.vue
client/src/outside/views/ClassList.vue
client/src/outside/views/LmsActivity.vue
client/src/outside/views/UnlinkedActivity.vue
client/src/store/modules/assignmentListStore.js
server/src/mcr/user/user-controller.js

Found that it is possible for activities to be unlinked to learning objects. This was not expected so there were many places in the code that assumed every Activity had a link to a Learning Object (called assignment in the code).  This PR addresses this situation and allows instructor users make connections for unlinked activities.

Fix issues with unlinked activities

---

client/package-lock.json
client/package.json
client/src/ehr-definitions/ehr-checkset.js

Safari does not support RegExp Lookbehind. The decamelize library uses this form of RegExp. To fix I removed the decamelize library from client and copied the little bit of code into the ehr-checkset.js file.

Fix Safari

---

client/src/outside/components/seed-struct/SeedPage.vue
client/src/outside/components/seed-struct/SeedStructural.vue
client/src/scss/_definitions.scss

On the condensed EHR view allow user to collapse table. This is important when a page has two or more tables and the orientation is vertical

Condensed view collapsible tables

---

client/src/app/components/AppFooter.vue
client/src/main.js
server/src/config/config.js

Reduce sentry sampling rates to avoid transaction overusage.
Add a means to test throwing an error on the client.

Vue client central error handler, tweak Sentry settings

---

deployment/d-c.yml
deployment/env-check.js
deployment/sample.env.site
edehr.org/scripts_edehr/edehr_db_backup.sh
edehr.org/scripts_edehr/edehr_db_restore.sh

Split the docker volumes used by the database container into three to allow for changing one without affecting the others.  For example, to be able to set the location of the backup files into a different location that the database itself.

Change docker volume declaration

---

client/src/helpers/axios-helper.js
client/src/helpers/page-controller.js
client/src/helpers/store-helper.js
client/src/helpers/web-socket-client.js
client/src/main.js
client/src/outside/views/Demo.vue
package-lock.json
package.json
server/src/mcr/auth/auth-controller.js
server/src/mcr/common/auth-util.js
server/src/server/push-server.js
server/src/server/server.js

Previous design created an event listener per connection and that's a problem because the system has limited event listeners.
So, redesigned to use a single listener for all connections. Decided to make the client code into a class rather than a function to improve separation of concerns.
Introduce new event when user "logs in" and "logs out".  Decided to use the moment the auth header is set/unset to fire this event.
The event is useful to close websocket connections.

Websocket single event listener

---

client/src/app/components/AppDialogShell.vue
client/src/ehr-definitions/ehr-page-defs.js
client/src/inside/components/page/EhrDialogForm.vue
client/src/outside/components/seed-struct/SeedPage.vue
client/src/outside/views/LearningObjects.vue
client/src/scss/styles/_forms.scss
client/src/store/modules/system.js
ehr-workspace/src/ehr-definitions/ehr-page-defs.js
makeEhrV2/generated/ehrDefs/ehr-page-defs.js
makeEhrV2/hashMapFile.json
makeEhrV2/raw_data/med-lab.txt
server/src/db/dbSeeder.server.spec.js
server/src/ehr-definitions/ehr-page-defs.js
server/src/mcr/assignment/assignment-controller.js
server/src/mcr/demo/demo-controller.js

The text in EHR forms is now larger and the dialog is larger too.
The instructors evaluation page will retain their selections of table collapse state.
Tweaks to the Urinalysis forms based on SME advice.
LObjs may not have seeds now. Made some adjustments for this situation.

Urinalysis teaks; seed structural table collapse state;  enlarge EHR forms

---

client/src/demos/erin-johns-seed-day2-end.json
client/src/ehr-definitions/ehr-page-defs.js
client/src/ehr-definitions/ehr-types.js
client/src/ehr-definitions/med-definitions/medOrder-model.js
client/src/helpers/page-controller.js
client/src/inside/components/page/EhrElementCalculatedBool.vue
client/src/inside/components/page/EhrElementForm.vue
client/src/inside/components/page/ehr-calc-text.js
client/src/scss/styles/_forms.scss
client/src/store/modules/mPatientStore.js
ehr-workspace/src/ehr-definitions/ehr-page-defs.js
ehr-workspace/src/ehr-definitions/ehr-types.js
ehr-workspace/src/ehr-definitions/med-definitions/medOrder-model.js
makeEhrV2/generated/ehrDefs/ehr-page-defs.js
makeEhrV2/hashMapFile.json
makeEhrV2/raw_data/current-mar.txt
makeEhrV2/raw_data/med-lab.txt
server/src/ehr-definitions/ehr-page-defs.js
server/src/ehr-definitions/ehr-types.js
server/src/ehr-definitions/med-definitions/medOrder-model.js

EhrOnlyDemo with mPatient fixed. Just needed to push the seed id into the mPatient store to be able to get the seed data
update the EHR only demo case study #2
MAR's summary of the med order
- include any injection location
- make the route and location human readable
Fix checkboxes on Chrome to remove extra line
EHR content updates
- MedLab Urinalysis, remove L,H,CL,CH options
- MED add second signature
MAR - remove mandatories until we do barscan checks. (nurses need to prepare the mar and then administer)
- make med order human readable
- add route and injection site to MAR
Calculated Bool -- to allow Med Orders to set 2nd sig req'd on MAR
Up EHR content
Med Order with 2nd Sig req'd
MAR with route, injection site, 2nd sig

EhrOnly, MAR, MedOrder, Checkboxes, CalBool, MedLab, 

---

client/src/directives/text-to-html.js
client/src/helpers/ehr-utils.js
client/src/helpers/mPatientHelper.js
client/src/outside/components/learning-object/LearningObjectActions.vue
client/src/store/modules/seedListStore.js
server/src/server/trace-api.js

The v-text-to-html directive was keeping previous data if the new content was empty.
The mPatient tab sorting hit a problem when a seed was yet to get a patient name.
Tracing on the server is reorganized to allow easier visual sorting.
Exporting of LObjs now include the seed.

Fix defects - Better LObj export import

---

client/src/ehr-definitions/med-definitions/mar-model.js
client/src/ehr-definitions/med-definitions/medOrder-model.js
client/src/ehr-definitions/med-definitions/mm-event.js
client/src/inside/components/mar/MarTabs.vue
client/src/inside/components/marV2/MarMedGrid.vue
client/src/scss/_definitions.scss
ehr-workspace/src/ehr-definitions/med-definitions/mar-model.js
ehr-workspace/src/ehr-definitions/med-definitions/medOrder-model.js
ehr-workspace/src/ehr-definitions/med-definitions/mm-event.js
server/src/ehr-definitions/med-definitions/mar-model.js
server/src/ehr-definitions/med-definitions/medOrder-model.js
server/src/ehr-definitions/med-definitions/mm-event.js

Remove the vertical day selector bars that no one could understand.
Replace with straight forward day selection buttons.
Also show the full date string calculated based on today and the simulation's encounter date
Provide info popup for each medication
Style MAR done button based on mar status
Let user select rows on MAR just to highlight the active row

MAR page rework a new design

---

client/src/appText.js
client/src/ehr-definitions/EhrDataModel.js
client/src/ehr-definitions/ehr-data-upgrade-v2.4.1.js
client/src/inside/components/page/EhrDialogForm.vue
client/src/inside/components/page/EhrElementCommon.vue
client/src/inside/components/page/EhrElementForm.vue
client/src/inside/components/page/ehr-helper.js
client/src/store/modules/visit.js
ehr-workspace/src/ehr-definitions/EhrDataModel.js
ehr-workspace/src/ehr-definitions/ehr-data-upgrade-v2.4.1.js
ehr-workspace/src/ehr-tests/ev2_4_1.spec.js
ehr-workspace/src/resources/for2-4-1.json
server/src/ehr-definitions/EhrDataModel.js
server/src/ehr-definitions/ehr-data-upgrade-v2.4.1.js
server/src/mcr/common/counters.spec.js
server/src/mcr/user/user.server.spec.js
server/src/mcr/visit/visit-controller.server.spec.js
server/src/test/package-lock.system.spec.js

Update allergies EHR data to move preexisting allergen to table
Correctly manage the record header when viewed and edited
When editing a row use the current sim time and care provider.
When viewing show the record data.
When cancelling record edit warn user that cancel means delete
update some server unit tests

Allergies, record headers, dialog cancel warnings
